### ISSUE TITLE
SocketException (0x2746): An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by blowers42** [okta/samples-aspnet-webforms#27]
I can run this sample code from visual studio via IISExpress using our OktaPreview.  I've taken the same code copied it to a web server.  Configured server app in our OktaPrevew.  When using this sample app from an IIS 10 web server I receive this stack trace when I login:

[SocketException (0x2746): An existing connection was forcibly closed by the remote host]    System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult) +8058794    System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult) +46  [IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.]    System.Net.TlsStream.EndWrite(IAsyncResult asyncResult) +305    System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar) +167  [WebException: The underlying connection was closed: An unexpected error occurred on a send.]    System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +762    System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +81  [HttpRequestException: An error occurred while sending the request.]    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__8.MoveNext() +702  [IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'.]    Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__8.MoveNext() +1169    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.IdentityModel.Protocols.OpenIdConnect.<GetAsync>d__3.MoveNext() +391    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__24.MoveNext() +865  [InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.]    Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__24.MoveNext() +1570    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Security.OpenIdConnect.<ApplyResponseChallengeAsync>d__c.MoveNext() +724    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Security.Infrastructure.<ApplyResponseCoreAsync>d__40.MoveNext() +349    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Security.Infrastructure.<ApplyResponseAsync>d__39.MoveNext() +447    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Security.Infrastructure.<TeardownAsync>d__34.MoveNext() +196    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Security.Infrastructure.<Invoke>d__5.MoveNext() +929    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__7.MoveNext() +197    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Security.Infrastructure.<Invoke>d__5.MoveNext() +735    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__7.MoveNext() +197    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__12.MoveNext() +192    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32    Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +118    System.Web.AsyncEventExecutionStep.InvokeEndHandler(IAsyncResult ar) +221    System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +115
--

paraphrasing  the browsers developer tools:
https://mydom.oktapreview.com/api/v1/authn   	OPTIONS		200
https://mydom.oktapreview.com/api/v1/authn   	POST                200  JSON with "status": "SUCCESS"
https://mydom.oktapreview.com/api/v1/authn   	GET			200
https://myserver.mydom.org/OktaPOC/Login.aspx 	POST		500  An existing connection was forcibly closed by the remote host....

I would like to know how to know why the connection was forcibly closed.  I've been through the logs of our firewalls and dont see any evidence that they closed the connection.

Best Regards, Allen

**Comment by bryanapellanes-okta** [comment]
@blowers42 ,
Thanks for reaching out.  Based on the stack trace you've provided, it appears that the underlying OIDC component is failing to retrieve configuration information.  These lines in the stack trace appear to have redacted the configuration url for your domain: 
```
[InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.]
and
[IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'.]
```

Using fiddler you should be able to see the requests that are failing, and that should lead to a better understanding of the issue.  You can download fiddler from here: [https://www.telerik.com/download/fiddler-everywhere](https://www.telerik.com/download/fiddler-everywhere).

**Comment by blowers42** [comment]
OK.  I’ll get ahold of fiddler and see what I can learn from that.

Best Regads, Allen

**Comment by blowers42** [comment]
I need to ask about alternatives.  Would an HAR file serve the same purpose?  Or a packet capture?  I am a bit leery of putting this traffic  thru a commercial proxy.

- Allen

**Comment by arvindkrishnakumar-okta** [comment]
@blowers42 Thanks for your question! Our .NET team will follow-up on this after the holidays.

**Comment by blowers42** [comment]
This turned out to be our firewall closing the connection.  Used some packet capturing to find it.  Our web server was blocked from reaching out for .../.well-known/openid-configuration  

- Allen
